#!/bin/bash

#REVISION=faaae4e76

# check platform
platform='unknown'
unamestr=`uname`

if [ "$unamestr" == 'Linux' ]; then
  platform='linux'
else
  platform='mac'
fi


TMPDIR=$(mktemp -d /tmp/git-latexdiff.XXXXXX)

#mkdir TMP/

latexdiff Revision0/thesis.tex thesis.tex > $TMPDIR/diff.tex
pdflatex -interaction nonstopmode -output-directory $TMPDIR $TMPDIR/diff.tex

if [ $platform == 'linux' ]; then
  atril $TMPDIR/diff.pdf
else
  open $TMPDIR/diff.pdf
fi

rm -rf $TMPDIR

exit $?
